name: "Sentinel GitHub Actions"
on:
  - pull_request
jobs:
  sentinel:
    name: "Sentinel"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Sentinel Format"
        uses: hashicorp/sentinel-github-actions@master
        with:
          stl_actions_version: 0.14.2
          stl_actions_subcommand: "fmt"
          stl_actions_working_dir: "."
          stl_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Sentinel Test"
        uses: hashicorp/sentinel-github-actions@master
        with:
          stl_actions_version: 0.14.2
          stl_actions_subcommand: "test"
          stl_actions_working_dir: "."
          stl_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
